/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import dinoModels.SaurioClass;
import utils.APIHandler;

/**
 *
 * @author DAM
 */
public class DataSaurioPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataSaurioPanel
     */
    public DataSaurioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tx_NombreSaurio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tx_Alimentacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tx_Edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CB_Poder = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("DATASAURIO");

        jPanel1.setLayout(new java.awt.GridLayout(4, 10, 2, 10));

        jLabel2.setText("Dinosaurio");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jPanel1.add(tx_NombreSaurio);

        jLabel3.setText("Alimentacion");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);

        Tx_Alimentacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(Tx_Alimentacion);

        jLabel4.setText("edad");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jPanel1.add(Tx_Edad);

        jLabel5.setText("Poder");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);

        CB_Poder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mordisco", "Fuego", "Ataque aereo" }));
        jPanel1.add(CB_Poder);

        jButton1.setBackground(new java.awt.Color(255, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("DinoCrear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var saurio = new SaurioClass();
       saurio.setNombreSaurio(tx_NombreSaurio.getText());
       saurio.setAlimentacion(Tx_Alimentacion.getText());
       saurio.setDinoAge(Integer.parseInt(Tx_Edad.getText()));
       saurio.setPoder((String)CB_Poder.getSelectedItem());
        
        Object respuestaCrear = APIHandler.createSaurio(saurio);
        tx_NombreSaurio.setText(null);
        Tx_Alimentacion.setText(null);
        Tx_Edad.setText(null);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Poder;
    private javax.swing.JTextField Tx_Alimentacion;
    private javax.swing.JTextField Tx_Edad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tx_NombreSaurio;
    // End of variables declaration//GEN-END:variables
}
